# Generated by Django 5.2.8 on 2026-02-03 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_user_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodewarsProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('honor', models.PositiveIntegerField(default=0)),
                ('leaderboard_position', models.PositiveIntegerField(default=0)),
                ('languages', models.JSONField(default=list)),
                ('total_completed_katas', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
        migrations.AddField(
            model_name='user',
            name='codewars_username',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='users_user_usernam_65d164_idx'),
        ),
        migrations.AddField(
            model_name='codewarsprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='codewars_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
