# Generated by Django 5.2.8 on 2026-02-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_codewarsprofile_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codewarsprofile",
            name="honor",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="codewarsprofile",
            name="languages",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="codewarsprofile",
            name="leaderboard_position",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="codewarsprofile",
            name="total_completed_katas",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
