# Generated by Django 5.2.8 on 2026-02-13 14:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_codewarsprofile_honor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="codewarsprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="codewarsprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
