# Generated by Django 5.2.8 on 2026-02-15 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_decks', to=settings.AUTH_USER_MODEL)),
                ('cards', models.ManyToManyField(related_name='decks', to='cards.card')),
                ('saved_by', models.ManyToManyField(blank=True, related_name='saved_decks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['title'], name='decks_deck_title_c6d24d_idx'), models.Index(fields=['-created_at'], name='decks_deck_created_11d709_idx')],
            },
        ),
    ]
