# Generated by Django 5.2.8 on 2026-02-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_remove_cardset_author_remove_cardset_cards_and_more'),
        ('repetitions', '0003_deckprogress_delete_cardsetprogress_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CardSet',
        ),
        migrations.AddIndex(
            model_name='deck',
            index=models.Index(fields=['title'], name='decks_deck_title_c6d24d_idx'),
        ),
        migrations.AddIndex(
            model_name='deck',
            index=models.Index(fields=['-created_at'], name='decks_deck_created_11d709_idx'),
        ),
    ]
