# Generated by Django 5.2.8 on 2025-11-27 12:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='card',
            name='cards_card_front_b54f13_idx',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='back',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='front',
            new_name='question',
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['question'], name='cards_card_questio_9f21e5_idx'),
        ),
    ]
