# Generated by Django 5.2.8 on 2026-02-16 11:02

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='answer',
            field=tinymce.models.HTMLField(),
        ),
    ]
