# Generated by Django 5.2.8 on 2025-11-29 11:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0004_cardset_saved_by_alter_card_author_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="saved_by",
            field=models.ManyToManyField(
                blank=True, related_name="saved_cards", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
