# Generated by Django 5.2.8 on 2026-01-28 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0006_cardsetprogress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardsetprogress",
            name="cardset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progresses",
                to="cards.cardset",
            ),
        ),
    ]
