# Generated by Django 5.2.8 on 2026-02-03 09:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0007_alter_cardsetprogress_cardset"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="card",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="cardset",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="cardsetprogress",
            options={"ordering": ["next_review_date"]},
        ),
        migrations.AddIndex(
            model_name="card",
            index=models.Index(
                fields=["-created_at"], name="cards_card_created_98fc81_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cardset",
            index=models.Index(
                fields=["-created_at"], name="cards_cards_created_8ae81a_idx"
            ),
        ),
    ]
