# Generated by Django 5.2.8 on 2026-02-12 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_alter_card_options_alter_cardset_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CardSetProgress',
        ),
    ]
