# Generated by Django 5.2.8 on 2026-02-12 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0009_delete_cardsetprogress"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cardset",
            name="author",
        ),
        migrations.RemoveField(
            model_name="cardset",
            name="cards",
        ),
        migrations.RemoveField(
            model_name="cardset",
            name="saved_by",
        ),
    ]
