# Generated by Django 5.2.8 on 2026-02-12 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_remove_cardset_author_remove_cardset_cards_and_more'),
        ('repetitions', '0002_alter_cardsetprogress_cardset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CardSet',
        ),
    ]
