# Generated by Django 5.2.8 on 2026-01-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="cover_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="projects/covers/"
            ),
        ),
    ]
