# Generated by Django 5.2.8 on 2026-03-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_project_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="cover_image",
            field=models.ImageField(
                blank=True, max_length=255, upload_to="projects/covers/"
            ),
        ),
    ]
