# Generated by Django 5.2.8 on 2025-12-11 13:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_card_saved_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardSetProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repetitions', models.PositiveIntegerField(default=0)),
                ('efactor', models.FloatField(default=2.5)),
                ('interval', models.PositiveIntegerField(default=0)),
                ('next_review_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_review_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardset_progresses', to='cards.card')),
                ('cardset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_progresses', to='cards.cardset')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardset_progresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['learner'], name='cards_cards_learner_ec70dd_idx'), models.Index(fields=['next_review_date'], name='cards_cards_next_re_99d76b_idx')],
                'unique_together': {('learner', 'cardset', 'card')},
            },
        ),
    ]
