# Generated by Django 5.2.8 on 2026-02-15 17:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        ('decks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeckProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repetitions', models.PositiveIntegerField(default=0)),
                ('efactor', models.FloatField(default=2.5)),
                ('interval', models.PositiveIntegerField(default=0)),
                ('next_review_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_review_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_progresses', to='cards.card')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='decks.deck')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_progresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_review_date'],
                'indexes': [models.Index(fields=['learner'], name='repetitions_learner_84be6e_idx'), models.Index(fields=['next_review_date'], name='repetitions_next_re_dcb155_idx')],
                'unique_together': {('learner', 'deck', 'card')},
            },
        ),
    ]
