# Generated by Django 5.2.8 on 2026-02-12 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0001_initial"),
        ("repetitions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardsetprogress",
            name="cardset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progresses",
                to="decks.cardset",
            ),
        ),
    ]
