# Generated by Django 5.2.8 on 2026-02-27 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
        ('repetitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='deckprogress',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_progresses', to='decks.deck'),
        ),
        migrations.AlterField(
            model_name='deckprogress',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_card_progresses', to=settings.AUTH_USER_MODEL),
        ),
    ]
